package com.ravikantsharma.designsystem

import androidx.compose.ui.graphics.Color

val ExManagerBlack = Color(0xFF1B1B1C)
val ExManagerDarkGrey = Color(0xFF44474B)
val ExManagerPurple = Color(0xFF5800C8)
val ExManagerWhite = Color(0xFFFFFFFF)
val ExManagerRed = Color(0xFFA40019)
val ExManagerPaleLavender = Color(0xFFFEF7FF)
val ExManagerLightGrey = Color(0xFF1D1A25)
val ExManagerPrimaryFixed = Color(0xFFEADDFF)
val ExManagerOnPrimaryFixed = Color(0xFF24005A)
val ExManagerSurfaceContainerLow = Color(0xFFF6F3F3)
val ExManagerSurfaceContainerLowest = Color(0xFFFFFFFF)
val ExManagerGreen = Color(0xFF29AC08)
val ExManagerPrimaryContainer = Color(0xFF8138FF)
val ExManagerOnPrimaryContainer = Color(0xFFFFFFFF)
val ExManagerInversePrimary = Color(0xFFD2BCFF)
val ExManagerSecondaryFixed = Color(0xFFE5EA58)
val ExManagerSecondaryContainer = Color(0xFFD2E750)
val ExManagerSecondaryFixedDim = Color(0xFFC9CE3E)
val ExManagerOnSecondaryContainer = Color(0xFF414300)
val ExManagerTertiaryContainer = Color(0xFFC4E0F9)
val ExManagerSecondary = Color(0xFF5F6200)
val ExManagerSuccess = Color(0xFF29AC08)
